CREATE TABLE users ( 
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE eintrag (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INT NOT NULL, 
	title VARCHAR(255) NOT NULL,
	textbe VARCHAR(1000) NOT NULL,
	date_create DATE NOT NULL,
	create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	kategorie INT
);

ALTER TABLE eintrag
	ADD CONSTRAINT FK_user_id FOREIGN KEY (user_id)
		REFERENCES users (id);
